### ISSUE TITLE
Player Oclussion Factor different in 2 scripts + Some questions

### ISSUE THREAD

**Issue by ElMoha943** [Guribo/UdonVoiceUtils#16] opened 2023-12-03 07:48 UTC
I believe all player occlusion factors should work in the same direction to avoid errors.

Player Audio Override
![image](https://github.com/Guribo/UdonVoiceUtils/assets/25410859/ddd308a0-4c5a-40bd-a632-97a9344e1e28)

Player Audio Configuration Model
![image](https://github.com/Guribo/UdonVoiceUtils/assets/25410859/fbe956e8-f0f2-48f7-8692-4e42a15d2541)

Having said that, i have some questions, sorry if they are too basic:
- If im not using the UI to let players change their settings, which script should i use to change the values for all players by default? Im guessing its DefaultConfiguration, but can i get rid of LocalConfiguration and MasterConfiguration?
- In the priority settings, a higher one its used first? i would appreciate a tooltip on that one!
- I have a muting system in place in my map right now which stops working when i add the addon, how can i implement a mute for an specific player and prevent the script from changing his settings again?

**Comment by ElMoha943** [comment] 2023-12-03 18:03
Thanx you so much for all your answers! i will use solution A since it seems easier to implement in my current system

**Comment by ElMoha943** [comment] 2023-12-04 13:40
Is there a way to make a microphone be heard in all channels? if not, could I request that feature?

**Comment by Guribo** [comment] 2023-12-04 18:36
This feature is not supported currently. However what you can try right now is extending the current microphone script or make your own:
1. For every private channel create a duplicate of the mics `PlayerAudioOverride` with all its dependencies
2. Adjust the channel on each one of them to match one of the used private channels
3. In the mic script add the player to each override and remove again when the players stops using the mic.

This is not a good solution tho as it will make the mic user lag during mic pickup and mic drop.

Thanks for the suggestion though, I will probably dedicate a few channels to this capability or maybe just add another boolean. I'll put it on my todo list :)

**Comment by Guribo** [comment] 2024-05-11 11:47
Can this be closed now?

**Closed** 2024-05-11 18:57 UTC
Labels: bug, Feedback/Review needed
