### ISSUE TITLE
Performance Issues in Large Instances

### ISSUE THREAD

**Issue by Kreyadian** [Guribo/UdonVoiceUtils#14] opened 2023-10-01 04:44 UTC
I've noticed stuttering and generally poor performance after spending some time and a large instance (60-80 people) with more than one override zone. I want to say it feels like a memory leak as it gets worse over time but not able to say for certain as the only way to replicate it is in an actual instance.
It doesn't seem to happen if there aren't any override zones so I would bet the issue is somewhere in there.

**Comment by Guribo** [comment] 2023-10-01 07:07
Thanks for letting me know, which version are you using? 0.8 or older? 1.0?

**Comment by Guribo** [comment] 2023-10-04 16:52
I did some investigation and I found out that this is most likely caused by excessive logging on my part.

In this example I have 100 players entering a zone all at once for example and it allocates >100 Mb of memory just for logging and the array stuff I am doing.

That is obviously sub-optimal to not say bad.

![image](https://github.com/Guribo/UdonVoiceUtils/assets/49484893/108fb12c-e41d-4b65-b230-73035c5e52dc)

I will address this issue before I release 1.0 officially.

**Comment by Guribo** [comment] 2023-10-05 18:10
I managed to address the issue and removed a large chunk of allocations: down from 115Mb for 100 players down to 9Mb:

![image](https://github.com/Guribo/UdonVoiceUtils/assets/49484893/b1b1e6f0-9b48-4692-95d4-b8659c99aef2)

There certainly is still some room for improvement as I have not yet transitioned to the new DataLists and DataDictionaries.

**Comment by Guribo** [comment] 2023-11-20 12:48
Resolved in 1.0.0-rc.1

**Closed by Guribo** 2023-11-20 12:48 UTC
